# Start with a base Debian image
FROM debian:trixie-slim

# Set environment variables
ENV TERM=xterm \
    XDG_RUNTIME_DIR="/var/tmp" \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install required packages
RUN curl -sL https://deb.nodesource.com/setup_22.x  | bash -
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    bash \
    git \
    nodejs \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    libsdl2-2.0-0 \
    libsdl2-image-2.0-0 \
    x11-xserver-utils \
    wget \
    unzip \
    curl \
    procps \
    build-essential \
    g++ \
    libc6 \
    libc6-dev \
    patchelf \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# Add basic trezor-user-env files
COPY ./ /trezor-user-env
WORKDIR /trezor-user-env

# Install a virtualenv for the app
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Install Poetry manually (to use with this venv)
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5
ENV PATH="/root/.local/bin:$PATH"

# Disable Poetry's own venv handling (we're inside one)
ENV POETRY_VIRTUALENVS_CREATE=false
RUN poetry env use /venv/bin/python

# Install deps
RUN poetry install --no-root --without dev

# Install trezorlib from Git
RUN pip install "git+https://github.com/trezor/trezor-firmware.git@main#egg=trezor&subdirectory=python"

# Execute scripts and clean up
RUN ./src/binaries/firmware/bin/download.sh
RUN ./src/binaries/trezord-go/bin/download.sh
RUN ./src/binaries/node-bridge/download.sh
# Patch emulator binaries
RUN cd src/binaries/firmware/bin && ./patch-bin.sh

# Command to run on container start
CMD ["/venv/bin/python", "src/main.py"]
