# Start with a base Debian image
FROM debian:trixie-slim

# Set environment variables
ENV TERM=xterm \
    XDG_RUNTIME_DIR="/var/tmp" \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install required packages
RUN curl -sL https://deb.nodesource.com/setup_22.x  | bash -
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    bash \
    git \
    nodejs \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    libsdl2-2.0-0 \
    libsdl2-image-2.0-0 \
    x11-xserver-utils \
    wget \
    unzip \
    curl \
    procps \
    build-essential \
    g++ \
    libc6 \
    libc6-dev \
    patchelf \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Need to export the installed libraries from poetry to requirements.txt,
# so it can be installed by pip, which is then needed for the custom
# trezorlib installation from git.
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"
RUN pip install --upgrade pip
RUN pip install poetry==2.1.3

# Copy just poetry files
WORKDIR /trezor-user-env
COPY ./pyproject.toml /trezor-user-env/
COPY ./poetry.lock /trezor-user-env/

RUN poetry self add poetry-plugin-export
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev
RUN pip install -r requirements.txt
RUN pip install "git+https://github.com/trezor/trezor-firmware.git@main#egg=trezor&subdirectory=python"

# Copy the rest of the files
COPY ./ /trezor-user-env

RUN ./src/binaries/firmware/bin/download.sh
RUN ./src/binaries/trezord-go/bin/download.sh
RUN ./src/binaries/node-bridge/download.sh
# Patch emulator binaries
RUN cd src/binaries/firmware/bin && ./patch-bin.sh

# Command to run on container start
CMD ["/venv/bin/python", "src/main.py"]
