name: "[Build] trezor-user-env image"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  build-tenv:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'trezor' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push trezor-user-env
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./docker/Dockerfile-debian
          platforms: linux/amd64,linux/arm64
          build-args: |
            EMULATOR_NIGHTLY_CACHE_BUST=${{ github.run_id }}-${{ github.run_attempt }}
          push: true
          # todo: using github.sha does not take into account downloaded binaries in Dockerfile.debian => sha stays same
          tags: |
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:latest

