name: "[Build] trezor-user-env image"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  build-tenv:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'trezor' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push trezor-user-env
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile-debian
          platforms: linux/amd64,linux/arm64
          push: true
          # todo: using github.sha does not take into account downloaded binaries in Dockerfile.debian => sha stays same
          tags: |
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:latest

