name: Build and push trezor-user-env image
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  build_and_push_tenv_image:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'trezor' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.TREZOR_BOT_USERNAME }}
          password: ${{ secrets.TREZOR_BOT_TOKEN }}
      -
        name: Build and push trezor-user-env
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/trezor-user-env:latest

