name: "[Check] validate trezor-user-env"

on: [pull_request]

jobs:
  validation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: latest trezorlib
        run: git clone --depth=1 https://github.com/trezor/trezor-firmware.git
      - name: "Install poetry"
        run: nix-shell --run "poetry install --no-root"
      #- name: Run style check
      #  run: nix-shell --run "poetry run make style_check"
      ## TODO: there is a mismatch between trezorlib versions we need to solve
      - name: Run code check
        run: nix-shell --run "poetry run make code_check"
