name: "[Test] controller tests"

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Setup Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Install dependencies with uv"
        run: nix-shell --run "uv sync"
      - name: "Download emulator binaries"
        run: nix-shell --run "uv run python ./src/binaries/firmware/bin/download.py all"
      - name: "Download node bridge"
        run: nix-shell --run "./src/binaries/node-bridge/download.sh"
      - name: "Patch emulator binaries"
        run: nix-shell --run "./src/binaries/firmware/bin/patch-bin.sh ./src/binaries/firmware/bin/"
      - name: Run tests
        run: nix-shell --run "uv run make test"
