name: "Controller tests"

on: [pull_request]


jobs:
  controller_test:
    runs-on: ubuntu-latest
    env:
      SDL_VIDEODRIVER: "dummy"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download emulator and bridge binaries
        run: nix-shell --run "./src/binaries/firmware/bin/download.sh && ./src/binaries/trezord-go/bin/download.sh"
      - name: "Install poetry"
        run: nix-shell --run "poetry install"
      - name: Run the tests
        run: nix-shell --run "poetry run make test"
