name: "Validation checks"

on: [pull_request]

jobs:
  validation_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Install poetry"
        run: nix-shell --run "poetry install"
      - name: Run style check
        run: nix-shell --run "poetry run make style_check"
      - name: Run code check
        run: nix-shell --run "poetry run make code_check"
